print ("Welcome to Funny Story One!")
name = input ("Please enter your name: ")
day = input ("Please enter a day of the week: ")
verb_past1 = input ("Please enter a past tense verb: ")
adj1 = input ("Please enter an adjective: ")
noun_pl1 = input ("Please enter a plural noun: ")
meal = input ("Please enter a meal (not a food): ")
verb1 = input ("Please enter a verb: ")
friend = input ("Please enter a friend's name: ")
verb2 = input ("Please enter another verb: ")
noun = input ("Please enter a noun: ")
verb3 = input ("Please enter another verb: ")
place = input ("Please enter a place: ") 
verb_past2 = input ("Please enter another past tense verb: ")
sky = input ("Please enter something you'd see in the sky: ")

print ("Last " + day + ", " + name + " woke up and " + verb_past1 + " out the window. ")
print ("There was a " + adj1 + " coating of " + noun_pl1 + " on the ground. After ")
print (meal + ", " + name + " went out into the yard to " + verb1 + " in the " + noun_pl1 + ". ")
print ("When " + name + " opened the door, there was " + friend + ", just getting ready to " + verb2 + " the ")
print (noun + ". 'Let's " + verb3 + " to the " + place + "', " + friend + " suggested. 'O.K., " + name + " replied. ")
print ("And they " + verb_past2 + " off into the " + sky + ".")
 